eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env

logging:
  level:
    org.springframework.cloud.config: DEBUG
