eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.internance: INFO
